In [1]:
#Welcome to Alpha Vantage! Your API key is: 6NY98HFWJ7HOKS8D. Please record this API key at a safe place for future data access.

# Import yfinance 
import numpy as np
import yfinance as yf   
 
# Get the data for the stock Apple by specifying the stock ticker, start date, and end date 
data = yf.download('AAPL','2020-01-01','2023-1-2') 
 
#data = yf.download(tickers='AAPL', period='1d', interval='1m') #to download 1 day recent data
# Plot the close prices 
import matplotlib.pyplot as plt 

#data.High.plot() 

x=np.array(data.Close)
y=np.array(data.Open)

delta=data.Close-data.Open

d=(np.array(delta)/data.Open)*100

print("Mean fluctuation is",np.mean(d))
print("Median fluctuation is",np.median(d))
print("Standara Deviation of the fluctuation is",np.std(d))

[*********************100%***********************]  1 of 1 completed
Mean fluctuation is 0.09373796085309273
Median fluctuation is 0.11190944459826124
Standara Deviation of the fluctuation is 1.7604728928254403


In [2]:
from sklearn.linear_model import LinearRegression
import numpy as np

## Data (Apple stock prices)
apple = x
n = len(apple)
print(n)
## One-liner
model = LinearRegression().fit(np.arange(n).reshape((n,1)), apple)

## Result & puzzle
print(model.predict([[3],[4]]))

756
[86.5079415  86.62490778]


In [3]:
import pandas as pd

data = yf.download('AAPL','2022-01-01','2023-1-2') 

df=pd.DataFrame(data)
X = df[['Open', 'High', 'Low', 'Volume']]
y = df['Close']


[*********************100%***********************]  1 of 1 completed


In [5]:
from sklearn.ensemble import RandomForestRegressor

# Select the features and target
#X = df[['open', 'high', 'low', 'volume']]
#y = df['close']

# Create a random forest regressor and train it on the data
regr = RandomForestRegressor(n_estimators=10)
regr.fit(X, y)

# Make a prediction on a new sample
prediction = regr.predict([[100, 105, 95, 10000]])
print(prediction)


[127.14300003]


# Using RNN

In [6]:
from keras.layers import LSTM, Dense
from keras.models import Sequential
from sklearn.model_selection import train_test_split


X = df[['Open', 'High', 'Low', 'Volume']].values
y = df['Close'].values

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Reshape the data for the RNN
X_train = np.reshape(X_train, (X_train.shape[0], 1, X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0], 1, X_test.shape[1]))

# Build the RNN model
model = Sequential()
model.add(LSTM(50, input_shape=(1, X_train.shape[2])))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')

# Train the model on the training data
model.fit(X_train, y_train, epochs=100, batch_size=32, verbose=1)

# Evaluate the model on the test data
score = model.evaluate(X_test, y_test, verbose=1)
print(f'Test loss: {score:.4f}')

# Make a prediction on a new sample
prediction = model.predict(np.array([[100, 105, 95, 10000]]).reshape(1, 1, 4))
print(prediction)


Epoch 1/100
7/7 [==============================] - 1s 3ms/step - loss: 24330.4180
Epoch 2/100
7/7 [==============================] - 0s 2ms/step - loss: 24309.9746
Epoch 3/100
7/7 [==============================] - 0s 2ms/step - loss: 24289.5605
Epoch 4/100
7/7 [==============================] - 0s 3ms/step - loss: 24269.2598
Epoch 5/100
7/7 [==============================] - 0s 7ms/step - loss: 24248.8203
Epoch 6/100
7/7 [==============================] - 0s 2ms/step - loss: 24228.5352
Epoch 7/100
7/7 [==============================] - 0s 2ms/step - loss: 24208.1621
Epoch 8/100
7/7 [==============================] - 0s 2ms/step - loss: 24187.8652
Epoch 9/100
7/7 [==============================] - 0s 2ms/step - loss: 24167.5430
Epoch 10/100
7/7 [==============================] - 0s 2ms/step - loss: 24147.2734
Epoch 11/100
7/7 [==============================] - 0s 3ms/step - loss: 24126.9570
Epoch 12/100
7/7 [==============================] - 0s 3ms/step - loss: 24106.7246
Epoch 13/100


[[[1.72779999e+02 1.73710007e+02 1.71660004e+02 5.63771000e+07]]

 [[1.72320007e+02 1.75179993e+02 1.70820007e+02 7.61383000e+07]]

 [[1.61149994e+02 1.62899994e+02 1.59820007e+02 7.33140000e+07]]

 [[1.78550003e+02 1.79610001e+02 1.76699997e+02 9.26332000e+07]]

 [[1.34289993e+02 1.37339996e+02 1.32160004e+02 9.15330000e+07]]

 [[1.51190002e+02 1.51470001e+02 1.48559998e+02 9.60299000e+07]]

 [[1.41070007e+02 1.42899994e+02 1.40270004e+02 8.52509000e+07]]

 [[1.29669998e+02 1.31029999e+02 1.25870003e+02 8.54384000e+07]]

 [[1.71339996e+02 1.73779999e+02 1.71089996e+02 8.04408000e+07]]

 [[1.36820007e+02 1.38589996e+02 1.35630005e+02 7.24338000e+07]]

 [[1.54789993e+02 1.57100006e+02 1.53610001e+02 8.79654000e+07]]

 [[1.45820007e+02 1.50009995e+02 1.44369995e+02 9.39797000e+07]]

 [[1.52220001e+02 1.53589996e+02 1.48559998e+02 8.98683000e+07]]

 [[1.54009995e+02 1.55039993e+02 1.52279999e+02 5.36239000e+07]]

 [[1.71779999e+02 1.71779999e+02 1.69199997e+02 7.65755000e+07]]

 [[1.49449